// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWV7ug-9qGTR-24VhXf49zdoG6BqHS6w',
    appId: '1:112809656661:web:90efec18c5c48b74402fdc',
    messagingSenderId: '112809656661',
    projectId: 'fluttergroceryapp-16d41',
    authDomain: 'fluttergroceryapp-16d41.firebaseapp.com',
    storageBucket: 'fluttergroceryapp-16d41.appspot.com',
    measurementId: 'G-WZMNYSWVE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_w-N7SshyoxozVN__ZRwmVO_dGUDHckU',
    appId: '1:112809656661:android:1b296680caab7735402fdc',
    messagingSenderId: '112809656661',
    projectId: 'fluttergroceryapp-16d41',
    storageBucket: 'fluttergroceryapp-16d41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANB4z4jDtVHQhd2XDgV9Wp_4I-mK8SJ-U',
    appId: '1:112809656661:ios:eaebd8087f52c835402fdc',
    messagingSenderId: '112809656661',
    projectId: 'fluttergroceryapp-16d41',
    storageBucket: 'fluttergroceryapp-16d41.appspot.com',
    iosClientId: '112809656661-f6dvi1lnvm5f161h85m73fkbtpl8nfnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryPlus',
  );
}
